### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by FelixSchwarz** [0x64746b/ctx_parser#9]
It seems this project doesn't come with a license statement. Would you mind adding one (for example by adding the license in the "LICENSE.txt" file and a sentence in README.md such as "This code is licensed under the terms of the ... license")? Otherwise it is impossible for me (and I guess many companies) to use your code.

If you don't have a strong preference for a specific license I'd like to suggest the MIT license.

**Comment by 0x64746b** [comment]
Sure. Happy hacking, dtk

**Comment by FelixSchwarz** [comment]
great, thanks :-)
